Full list view
anetaszynal/movies_browser pull request #10
Opened 2020-10-14 18:51 UTC by damdlani

Complete people and movies page, all RWD, enjoy!

2020-10-14 19:04 UTC, anetaszynal commented on src/common/components/Header/styled.js
>          align-content: center;
What do you think to add this property to Subheader styles and remove this media ?

2020-10-14 19:10 UTC, anetaszynal commented on src/features/movies/MoviesPage/index.js
> +      return productionYear;
Will you need this feature somewhere else? What do you think about moving this function outside?

2020-10-14 19:12 UTC, anetaszynal commented on src/features/movies/MoviesPage/index.js
> +                        description={result.overview}
What do you think about the values ​​of individual attributes being neutral?

2020-10-14 19:13 UTC, anetaszynal commented on src/features/movies/MoviesPage/index.js
> +                        description={result.overview}
What do you think about the values ​​of individual attributes being neutral?

2020-10-14 19:14 UTC, anetaszynal requested changes
Nice job ;)

2020-10-15 07:35 UTC, damdlani commented on src/common/components/Header/styled.js
>          align-content: center;
Unfortunatelly, it won't work then. In subheader there is align-content: space-between, which keeps it up to project view. Nevertheless it is Michał's job, I just deleted px and noticed that previous media is needless

2020-10-15 07:37 UTC, damdlani commented on src/features/movies/MoviesPage/index.js
> +      return productionYear;
Actually I would need it and getGenre in Singlepage movie, so I'll move both of them outside

2020-10-15 08:14 UTC, damdlani commented on src/features/movies/MoviesPage/index.js
> +      return productionYear;
Done. useMovieDetail. It is to be changed in future, while working on singlePage, because it will get different API

2020-10-15 08:16 UTC, anetaszynal approved these changes

2020-10-15 08:47 UTC, merged