MoviesPage structure + example Tile elements
anetaszynal/movies_browser pull request #3
Opened 2020-10-09 09:46 UTC by MikeAdamczyk

2020-10-09 11:33 UTC, anetaszynal commented on public/index.html
> +<html lang="pl">
I think that we should use english language according to instruction.

2020-10-09 11:52 UTC, anetaszynal commented on src/App.js
> +export default () => (
Please keep the previous name for better consistency

2020-10-09 12:04 UTC, anetaszynal commented on src/GlobalStyle.js
> +        margin: 0px auto 103px;
It seems that this margin should be added to the pagination.

2020-10-09 12:06 UTC, damdlani reviewed
Great job!

2020-10-09 12:06 UTC, damdlani commented on src/common/components/Paging/styled.js
> +    justify-content: center;
It works for `display: flex` which isn't set here. Btw text-align does the same thing.

2020-10-09 12:06 UTC, damdlani commented on src/common/components/Title/styled.js
> +    margin: 56px 0 24px 0;
line-height: 120%; is missing :)

2020-10-09 12:07 UTC, anetaszynal commented on src/common/components/Container/index.js
> +    background: white;
border radius is missing

2020-10-09 12:15 UTC, anetaszynal commented on src/common/components/Header/styled.js
> +export const HeaderBox = styled.div`
What do you think to use <header> here?

2020-10-09 12:17 UTC, anetaszynal commented on src/common/components/Header/styled.js
> +    height: 94px;
How the subheader is used? What's in it?

2020-10-09 12:24 UTC, anetaszynal commented on src/common/components/Search/styled.js
> +    box-sizing: border-box;
In my opinion, it is not necessary here. You declare it earlier

2020-10-09 13:29 UTC, anetaszynal commented on src/common/components/Container/index.js
> +export const Container = styled.div`
What do you think about applying for example <main> ?

2020-10-09 13:36 UTC, anetaszynal commented on src/common/components/Container/index.js
> +    padding: 30px;
Use theme, please ;)

2020-10-09 13:40 UTC, anetaszynal commented on src/common/components/Container/index.js
> +    padding: 30px;
I think that you should use 16px padding

2020-10-09 13:55 UTC, anetaszynal commented on src/common/components/Menu/Logo/index.js
> +export const Logo = styled.a`
width is missed

2020-10-09 13:58 UTC, anetaszynal commented on src/common/components/Paging/styled.js
> +    padding: 11px;
Do you need it?

2020-10-09 14:00 UTC, anetaszynal commented on src/common/components/Paging/styled.js
> +    max-width: 1368px;
In my opinion, max- width should be 525px

2020-10-09 14:01 UTC, anetaszynal commented on src/common/components/Paging/styled.js
> +    max-width: 1368px;
Isn't the width constant?

2020-10-09 14:14 UTC, anetaszynal commented on src/features/movies/MoviesPage/index.js
> +import { Header } from "../../../common/components/Header/index";
Could you change name for better consistency ?

2020-10-09 14:17 UTC, anetaszynal requested changes
It's nice that you did so much. I added a few suggestions in the comments.

2020-10-12 22:54 UTC, MikeAdamczyk commented on src/common/components/Header/styled.js
> + `;
it's 100% by default :)

2020-10-12 23:08 UTC, MikeAdamczyk commented on src/common/components/Header/styled.js
> +    height: 94px;
Subheader is needed to set position of menu and search input in proper way. Subheader height: 100% equals 88px, I don't know why :)  so I set min-height: 94px, later on it is changed on the mobile view for 142px.

2020-10-12 23:15 UTC, MikeAdamczyk commented on src/common/components/Title/styled.js
> +    margin: 56px 0 24px 0;
done :)

2020-10-12 23:16 UTC, MikeAdamczyk commented on src/common/components/Container/index.js
> +    background: white;
it was example Tile, already deleted ;)

2020-10-12 23:18 UTC, MikeAdamczyk commented on src/common/components/Header/styled.js
> +export const HeaderBox = styled.div`
Name for this section is used according to the project :)

2020-10-12 23:51 UTC, MikeAdamczyk commented on src/common/components/Container/index.js
> +export const Container = styled.div`
done :) additionally divided for MoviesContainer and PeopleContainer

2020-10-12 23:53 UTC, MikeAdamczyk commented on src/common/components/Container/index.js
> +    font-size: 24px;
nope ;) it's just a plug for development :)

2020-10-12 23:57 UTC, MikeAdamczyk commented on src/common/components/Menu/Logo/index.js
> +export const Logo = styled.a`
no need, <img/> and <p> have it's own width and fill it :)

2020-10-12 23:57 UTC, MikeAdamczyk commented on src/common/components/Paging/styled.js
> +    padding: 11px;
plug for development ;)

2020-10-12 23:59 UTC, MikeAdamczyk commented on src/common/components/Paging/styled.js
> +    max-width: 1368px;
will be developed later, it's just a plug

2020-10-13 00:00 UTC, MikeAdamczyk commented on src/features/movies/MoviesPage/index.js
> +import { Header } from "../../../common/components/Header/index";
which name?

2020-10-13 12:05 UTC, anetaszynal commented on src/common/components/Header/styled.js
> +export const HeaderBox = styled.div`
I meant replacing div with header tag ;)

2020-10-13 12:16 UTC, MikeAdamczyk commented on src/common/components/Header/styled.js
> +export const HeaderBox = styled.div`
OK, that's good idea :) DONE!

2020-10-13 12:22 UTC, anetaszynal commented on src/common/components/Header/styled.js
> +export const HeaderBox = styled.div`
Sorry, it's ok ;)

2020-10-13 12:23 UTC, anetaszynal approved these changes
Good job! For my part, everything is fine 😉

2020-10-13 16:44 UTC, merged