Movie list/tile element
anetaszynal/movies_browser pull request #4
Opened 2020-10-09 12:20 UTC by damdlani

2020-10-09 14:57 UTC, anetaszynal commented on src/components/Tile/styled.js
> +    margin: 100px auto;
Isn't it 56 px? (150-94)

2020-10-10 12:22 UTC, anetaszynal commented on src/components/Tile/styled.js
> +    max-width: 1368px;
I think it is unnecessary here.

2020-10-10 12:29 UTC, anetaszynal commented on src/components/Tile/styled.js
> +    box-shadow: 0px 4px 12px rgba(186, 199, 213, 0.5);
border-radius is missed

2020-10-10 12:40 UTC, anetaszynal commented on src/components/Tile/styled.js
> +    padding: 0px 0px 0px 40px;
Could you tell me where these values ​​come from? I can't see them. Wouldn't the grid be a better solution here and the grid-gap?

2020-10-10 13:52 UTC, anetaszynal commented on src/components/Tile/styled.js
> +        font-weight: 500;
In movie details font weight is 400

2020-10-10 13:52 UTC, anetaszynal commented on src/components/Tile/styled.js
> +        font-size: 22px;
line-heigh is missing and position is diffrent.

2020-10-10 15:10 UTC, anetaszynal commented on src/components/Tile/styled.js
> +export const Header = styled.h1`
In my opinion it should be h2.

2020-10-10 15:26 UTC, anetaszynal requested changes
Good job! 😉 Please consider using grid.

2020-10-10 16:02 UTC, damdlani commented on src/components/Tile/styled.js
> +    padding: 0px 0px 0px 40px;
I forgot to delete it. I used it just to better see the element during creating. Grid should be used in Michał's tile container.

2020-10-10 16:04 UTC, damdlani commented on src/components/Tile/styled.js
> +export const Header = styled.h1`
I wondered about it. But where is h1 used then? If nowhere, I can't see a better place for it

2020-10-11 06:37 UTC, damdlani commented on src/components/Tile/styled.js
> +export const Header = styled.h1`
Right, h1 should be used for container title, not movie title

2020-10-11 06:37 UTC, damdlani commented on src/components/Tile/styled.js
> +        font-weight: 500;
Changed it ;)

2020-10-11 06:39 UTC, damdlani commented on src/components/Tile/styled.js
> +        font-size: 22px;
Changed it ;)

2020-10-11 07:30 UTC, anetaszynal approved these changes

2020-10-11 07:35 UTC, merged