Fix structure
anetaszynal/movies_browser pull request #9
Opened 2020-10-14 16:46 UTC by MikeAdamczyk

2020-10-14 19:24 UTC, anetaszynal commented on src/common/Containers/index.js
>          margin-bottom: 16px;
I think you can use the shortcut (margin: 0 16px 16px)

2020-10-14 19:25 UTC, anetaszynal commented on src/common/Containers/index.js
> +    @media (max-width: ${({ theme }) => theme.breakpoints.medium}){
You have two, very similar styles. What do you think to join them ?

2020-10-14 19:28 UTC, anetaszynal requested changes
👍🏻

2020-10-15 07:24 UTC, MikeAdamczyk commented on src/common/Containers/index.js
>          margin-bottom: 16px;
of course :)

2020-10-15 08:01 UTC, MikeAdamczyk commented on src/common/Containers/index.js
> +    @media (max-width: ${({ theme }) => theme.breakpoints.medium}){
done :)

2020-10-15 08:08 UTC, anetaszynal approved these changes

2020-10-15 08:10 UTC, merged